GOHOSTOS:=$(shell go env GOHOSTOS)
GOPATH:=$(shell go env GOPATH)
VERSION=$(shell git describe --tags --always 2>/dev/null || echo "dev")
COMPOSE_FILE:=./docker/docker-compose.yml

.PHONY: init
# init env：安装代码生成所需工具
init:
	go install github.com/google/wire/cmd/wire@latest

.PHONY: generate
# 生成 wire 依赖注入代码、整理依赖
generate:
	go generate ./...
	go mod tidy

# ==================== 构建命令 ====================

.PHONY: build-api
# 构建 API 服务
build-api:
	mkdir -p bin/ && go build -ldflags "-X main.Version=$(VERSION)" -o ./bin/api ./cmd/services/api

.PHONY: build
# 构建全部服务
build: build-api

# ==================== 本地运行 ====================

.PHONY: run-api
# 运行 API 服务
run-api:
	go run ./cmd/services/api

# ==================== Docker ====================

.PHONY: up
# 启动本地依赖容器
up:
	docker-compose -f $(COMPOSE_FILE) up -d

.PHONY: clean
# 清理本地依赖容器
clean:
	docker-compose -f $(COMPOSE_FILE) down --volumes --remove-orphans

.PHONY: test
test:
	go test ./...

.PHONY: ci_lint
ci_lint:
	golangci-lint run

# show help
help:
	@echo ''
	@echo 'Usage:'
	@echo ' make [target]'
	@echo ''
	@echo 'Targets:'
	@awk '/^[a-zA-Z\-\_0-9]+:/ { \
	helpMessage = match(lastLine, /^# (.*)/); \
		if (helpMessage) { \
			helpCommand = substr($$1, 0, index($$1, ":")); \
			helpMessage = substr(lastLine, RSTART + 2, RLENGTH); \
			printf "\033[36m%-22s\033[0m %s\n", helpCommand,helpMessage; \
		} \
	} \
	{ lastLine = $$0 }' $(MAKEFILE_LIST)

.DEFAULT_GOAL := help
